accounts/urls.py
from django.urls import path 
from . import views

urlpatterns = [
	path('login/',views.LoginView.as_view(),name='login'),
	path('logout/',views.LogoutView.as_view(),name='logout'),
]

audit/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('', views.AuditListView.as_view(),name='audits'),
	path('<int:pk>/',views.AuditDetailView.as_view(),name='rules'),
	path('detail/<int:pk>/',views.AuditRankingView.as_view(),name='detail'),
	path('<int:audit_pk>/<int:pk>/',views.RuleDetailView.as_view(),name='numerals'),
	path('<int:audit_pk>/<int:rule_pk>/<int:pk>/',views.NumeralDetailView.as_view(),name='questions'),
	path('<int:audit_pk>/<int:rule_pk>/<int:numeral_pk>/<int:pk>',views.QuestionUpdateView.as_view(),name='question'),		
	path('new/', views.AuditCreateView.as_view(),name='create_audit'),
	path('new/rule/', views.RuleCreateView.as_view(),name='create_rule'),
	path('new/numeral', views.NumeralCreateView.as_view(),name='create_numeral'),
	path('new/question', views.QuestionCreateView.as_view(), name='create_question'),

]

audithor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='home.html'), name='home'),
    path('audits/',include(('audit.urls','audit'), namespace='audit')),
	path('',include(('accounts.urls','accounts'),namespace='accounts')),    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Audithor - {% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/icon.ico' %}">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/agency.css' %}" rel="stylesheet">

  </head>

  <body id="page-top" class="bg-light">
    {% include "nav.html" %}
    {% block container %}
    
    {% endblock container %}
    {% include "footer.html" %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Contact form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>
    <script>
        $(document).ready(function () {
            if ($("body").height() <  $(window).height()) {
            $("footer").css({"position":"absolute", "bottom" : "0px"});
            }
        });
    </script>
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/agency.min.js' %}"></script>
  </body>
</html>

templates/footer.html
<!-- Footer -->

<footer class="w-100">
  <hr>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright font-weight-bold">Copyright &copy; Audithor 2019</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li class="list-inline-item font-weight-bold">
            <a href="#">Privacy Policy</a>
          </li>
          <li class="list-inline-item font-weight-bold">
            <a href="#">Terms of Use</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/home.html
{% extends "base.html" %}
{% block title %}
Inicio
{% endblock title %}
{% block container %}
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">Bienvenido!</div>
      <div class="intro-heading text-uppercase">¿Listo para auditar?</div>
      {% if user.is_anonymous %}
      <a class="btn btn-warning btn-xl text-uppercase js-scroll-trigger scroll" href="{% url 'accounts:login' %}">Iniciar sesión</a>
      {% else %}
      <div class="row justify-content-center">
        <a class="btn btn-warning btn-xl text-uppercase js-scroll-trigger col-md-4 scroll d-none d-md-block" href="#go">Crea una nueva auditoria</a>
        
      </div>
      <a class="btn btn-warning btn text-uppercase js-scroll-trigger scroll d-block btn-xl d-sm-none" href="#go">Nueva auditoria</a>
      {% endif %}
    </div>
  </div>
</header>
{% if not user.is_anonymous %}
<section id="go">
  <div class="container">
    <h3 class="text-uppercase text-center mb-5">Datos de la Auditoria</h3>
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 border rounded  pt-3 pl-3 pr-3 ml-3 mr-3 bg-white"> 
        <form action="{% url 'audit:create_audit' %}" method="POST">
          <h4 class="text-center">Generales</h4>
          {% csrf_token %}
          <div class="form-group font-weight-bold">
            <label for=""><i class="fas fa-user-cog pr-1"></i>Nombre del Auditor</label>
            <input name="auditor_name" id="method" class="form-control">
          </div>
          <div class="form-group font-weight-bold">
            <label for=""><i class="fas fa-cog pr-1"></i>Proceso a Auditar</label>
            <input name="process_to_be_audited" id="method" class="form-control">
          </div>
          <div class="form-group font-weight-bold">
            <label for=""><i class="fas fa-location-arrow pr-1"></i>Alcance de la Auditoria</label>
            <input name="audit_scope" id="method" class="form-control">
          </div>
          <div class="form-group font-weight-bold">
            <label for=""><i class="fas fa-calendar-alt pr-1"></i>Fecha de la Auditoria</label>
            <input type="date" name="date" class="form-control">
          </div>
          <hr>
          <h4 class="text-center">Datos del Auditado</h4>
          <div class="form-group font-weight-bold">
            <label for=""><i class="fas fa-user-tie pr-1"></i>Nombre del Auditado</label>
            <input name="audited_name" id="method" class="form-control">
          </div>
          <div class="form-group font-weight-bold">
            <label for=""><i class="fas fa-briefcase pr-1"></i>Trabajo del Auditado</label>
            <input name="audited_job" id="method" class="form-control">
          </div>
          <div class="form-group font-weight-bold">
            <label for=""><i class="fas fa-phone pr-1"></i>Telefono</label>
            <input name="audited_phone_number" id="method" class="form-control">
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-warning col">Iniciar Auditoria</button>
          </div>      
        </form>
      </div>            
    </div>
  </div>
</section>    
{% endif %}
{% endblock container %}

templates/nav.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top" id="mainNav">
	<div class="container">
		<a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}"><i class="fas fa-gavel pr-2"></i>Audithor</a>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
			<i class="fas fa-bars"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav text-uppercase ml-auto">
				{% if not user.is_anonymous %}
				<li class="nav-item">
					<a class="nav-link js-scroll-trigger font-weight-bold" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i></i>Cerrar sesión</a>
				</li>
				<li class="nav-item">
					<a class="nav-link js-scroll-trigger font-weight-bold" href="{% url 'audit:audits' %}"><i class="fas fa-clipboard-list pr-1"></i>Ver Auditorias</a>
				</li>
				{% endif %}
        		<!--{% if audit %} ######### Tratar de hacer que se muestre en todas las vistas desde que se da al boton "Revisar"
        		<li class="nav-item">
          			<a class="nav-link js-scroll-trigger font-weight-bold" href="{% url 'audit:detail' audit.pk %}"><i class="far fa-chart-bar pr-1"></i>Ver estadisticas</a>
        		</li>
        		{% endif %}-->
    		</ul>
		</div>
	</div>
</nav>