audit/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('', views.AuditListView.as_view(),name='audits'),
	path('<int:pk>/',views.AuditDetailView.as_view(),name='rules'),
	path('detail/<int:pk>/',views.AuditRankingView.as_view(),name='detail'),
	path('<int:audit_pk>/<int:pk>/',views.RuleDetailView.as_view(),name='numerals'),
	path('<int:audit_pk>/<int:rule_pk>/<int:pk>/',views.NumeralDetailView.as_view(),name='questions'),
	path('<int:audit_pk>/<int:rule_pk>/<int:numeral_pk>/<int:pk>',views.QuestionUpdateView.as_view(),name='question'),		
	path('new/', views.AuditCreateView.as_view(),name='create_audit'),
	path('new/rule/', views.RuleCreateView.as_view(),name='create_rule'),
	path('new/numeral', views.NumeralCreateView.as_view(),name='create_numeral'),
	path('new/question', views.QuestionCreateView.as_view(), name='create_question'),

]

audithor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='home.html'), name='home'),
    path('audits/',include(('audit.urls','audit'), namespace='audit')),
	path('',include(('accounts.urls','accounts'),namespace='accounts')),    
]

audit/models.py
from django.db import models

# Create your models here.

class Audit(models.Model):
	"""este es el modelo que almacenará los datos mas generales de la auditoria"""
	auditor_name = models.CharField(max_length=50)
	audited_name = models.CharField(max_length=50)
	audited_job = models.CharField(max_length=255)
	process_to_be_audited = models.CharField(max_length=100)
	audit_scope = models.CharField(max_length=255)
	audited_phone_number = models.CharField(max_length=15)
	date = models.DateField()

	#metadata

	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.process_to_be_audited

class Rule(models.Model):
	audit = models.OneToOneField(Audit, on_delete=models.CASCADE)
	rule_name = models.CharField(max_length=50)
	rule_title = models.CharField(max_length=100)

	#metadata

	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.rule_name
 	
class Numeral(models.Model):
	rule = models.ForeignKey(Rule, on_delete=models.CASCADE)
	numeral = models.CharField(max_length=8)
	title = models.CharField(max_length=255)

	#metadata

	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return '{}) {}'.format(self.numeral,self.title)

class Question(models.Model):
	CONFLICTS = (
		('none','Ninguno'),
		('observation','Observación'),
		('find','Hallazgo'),
	)

	numeral = models.ForeignKey(Numeral, on_delete=models.CASCADE)
	question = models.CharField(max_length=255)
	method = models.TextField(max_length=255, blank=True,null=True)
	conflict = models.CharField(max_length=11, choices=CONFLICTS, blank=True, null=True)
	conflict_description = models.TextField(blank=True,null=True)
	evidence = models.ImageField(upload_to='evidences',blank=True,null=True)

	#metadata

	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.question

audit/forms.py
from django import forms
from . import models 

class AuditCreateForm(forms.ModelForm):
	class Meta:
		model = models.Audit
		fields = [
			'auditor_name',
			'audited_name',
			'audited_job',
			'process_to_be_audited',
			'audit_scope',
			'audited_phone_number',
			'date'
		]

class RuleCreateForm(forms.ModelForm):
	"""docstring for RuleCreateForm"""
	class Meta:
		model = models.Rule
		fields = [
			'audit',
			'rule_name',
			'rule_title'
		]

class NumeralCreateForm(forms.ModelForm):
	class Meta:
		model = models.Numeral
		fields = [
			'rule',
			'numeral',
			'title'
		]

class QuestionCreateForm(forms.ModelForm):
	"""docstring for QuestionCreateForm"""
	class Meta:
		model = models.Question
		fields = [
			'numeral',
			'question'
		]

audit/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from .models import Audit, Rule, Numeral, Question
from django.urls import reverse_lazy
from django.http import Http404
from .forms import AuditCreateForm, RuleCreateForm, NumeralCreateForm, QuestionCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class AuditListView(LoginRequiredMixin, ListView):
    model = Audit
    template_name = "audit/audits.html"
    context_object_name = 'audits'
    paginate_by = 5

class AuditDetailView(LoginRequiredMixin, DetailView):
    model = Audit
    template_name = "audit/rules.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rules = Rule.objects.filter(audit=self.get_object())
        context['rules'] = rules
        return context

class RuleDetailView(LoginRequiredMixin, DetailView):
    model = Rule
    template_name = "audit/numerals.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        numerals = Numeral.objects.filter(rule=self.get_object())
        context['numerals'] = numerals
        return context

class NumeralDetailView(LoginRequiredMixin, DetailView):
    model = Numeral
    template_name = "audit/questions.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        questions = Question.objects.filter(numeral = self.get_object())
        numeral = self.get_object()
        last = numeral.pk -1
        next = numeral.pk +1
        try:
            if Numeral.objects.get(pk=last):
                context['last']=last
        except Exception as e:
            pass
        try:
            if Numeral.objects.get(pk=next):
                context['next']=next
        except Exception as e:
            pass
        context['questions'] = questions
        return context

class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    template_name = "audit/question.html"
    fields = ['question','method','conflict','conflict_description','evidence']

    def get_success_url(self):
    	question = self.get_object()
    	audit = Audit.objects.get(pk=question.numeral.rule.audit.pk)
    	rule = Rule.objects.get(pk=question.numeral.rule.pk)
    	numeral = Numeral.objects.get(pk=question.numeral.pk)
    	return reverse_lazy('audit:questions', kwargs={
    		'audit_pk':audit.pk,
    		'rule_pk':rule.pk,
    		'pk':numeral.pk
    		})       

class AuditRankingView(LoginRequiredMixin, DetailView):
    model = Audit
    template_name = "audit/ranking.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        audit = self.get_object()
        questions = Question.objects.filter(numeral__rule__audit=audit)
        total_questions = len(questions)
        questions_none = len(questions.filter(conflict='none'))
        questions_observation = len(questions.filter(conflict='observation'))
        questions_find = len(questions.filter(conflict='find'))
        questions_none_percent = (questions_none*100)/total_questions
        questions_find_percent = (questions_find*100)/total_questions
        questions_observation_percent = (questions_observation*100)/total_questions
        unanswered_questions = total_questions-(questions_observation+questions_find+questions_none)
        unanswered_percent = (unanswered_questions*100)/total_questions
        context['questions'] = {
            'questions':questions,
            'total':total_questions,
            'observation':questions_observation,
            'find':questions_find,
            'none':questions_none,
            'none_percent':questions_none_percent,
            'find_percent':questions_find_percent,
            'observation_percent':questions_observation_percent,
            'unanswered_questions':unanswered_questions,
            'unanswered_percent':unanswered_percent
        }
        return context

class AuditCreateView(LoginRequiredMixin, CreateView):
    template_name = "audit/create_audit.html"
    form_class = AuditCreateForm
    success_url = reverse_lazy('audit:audits')

class RuleCreateView(LoginRequiredMixin, CreateView):
    template_name = "audit/create_rule.html"
    form_class = RuleCreateForm
    success_url = reverse_lazy('audit:audits')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['audits'] = Audit.objects.filter(rule=None)
        return context

class NumeralCreateView(LoginRequiredMixin, CreateView):
    template_name = "audit/create_numeral.html"
    form_class = NumeralCreateForm
    success_url = reverse_lazy('audit:audits')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rules = Rule.objects.all()
        context['rules'] = rules
        return context

class QuestionCreateView(LoginRequiredMixin, CreateView):
    template_name = "audit/create_question.html"
    form_class = QuestionCreateForm
    success_url = reverse_lazy('audit:audits')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        numerals = Numeral.objects.all()
        context['numerals']=numerals
        return context

templates/audit/audits.html
{% extends "base.html" %}
{% block title %}
Audits
{% endblock title %}
{% block container %}
<div class="container" style="margin-top: 5rem;">
	<div class="jumbotron text-center">
		<h1 class="text-uppercase">Auditorias</h1>
		<hr>
		<h5>Selecciona el proceso que vas a auditar.</h5>
	</div>
	<div class="container">
		<!--<a href="" class="btn btn-success btn-sm btn-block text-uppercase"><i class="fas fa-plus pr-1"></i>Crear nueva Auditoria</a>-->
	</div>
	{% for audit in audits %}
	<div class="row justify-content-center">
		<div class="col-sm-12 col-md-10 col-lg-8">
			<div class="card mt-4 ml-4 mr-4">
				<div class="card-header">
					<div class="row">
						<div class="col-sm-12 col-md-9 col-lg-9">
							<span class="align-middle text-uppercase font-weight-bold"><i class="fas fa-cog pr-1"></i>Proceso a auditar: </span>
							<span class="align-middle">{{audit|title}}</span>
						</div>
						<div class="col">
							<!--Button for desktop-->
							{% if audit.rule %}
							<a href="{% url 'audit:rules' audit.pk %}" class="btn btn-warning float-right btn-sm d-none d-sm-none d-md-block"><i class="far fa-eye pr-1"></i>Revisar</a>
							{% endif %}
							{% if not audit.rule %}
							<a href="{% url 'audit:create_rule' %}" class="btn btn-warning float-right btn-sm d-none d-sm-none d-md-block"><i class="fas fa-plus pr-1"></i>Asignar</a>
							{% endif %}
						</div>
					</div>
				</div>
				{% if not audit.rule %}
				<div class="alert alert-danger m-0 p-0 text-center" role="alert">
					<small>Actualmente este proceso no tiene normas enlazadas. Por favor asigne una nueva.</small>
				</div>
				{% endif %}
				<div class="card-body">

					<h6 class="card-title"><i class="fas fa-user-tie pr-1"></i>Persona encargada del proceso: {{audit.audited_name|title}}</h6>
					<p class="card-text m-0 font-weight-bold"><i class="fas fa-location-arrow pr-1"></i>Alcance de la auditoria: </p>
					<small class="card-text">{{audit.audit_scope|capfirst}}.</small>
					{% if audit.rule %}
					<div class="mt-3">
						<a class="btn btn-info float-right btn-sm col" href="{% url 'audit:detail' audit.pk %}"><i class="far fa-chart-bar pr-1"></i>Ver Estadisticas</a>
					</div>
					{% endif %}


				</div>
				<!--Button for mobile-->
				{% if audit.rule %}
				<a href="{% url 'audit:rules' audit.pk %}" class="btn btn-primary btn-sm d-block d-sm-block d-md-none"><i class="far fa-eye pr-1"></i>Revisar</a>
				{% endif %}
				{% if not audit.rule %}
				<a href="{% url 'audit:create_rule' %}" class="btn btn-primary btn-sm d-block d-sm-block d-md-none"><i class="fas fa-plus pr-1"></i>Asignar</a>
				{% endif %}
			</div>
		</div>
	</div>
	{% endfor %}
	<ul class="pagination float-right">
		{% if page_obj.has_previous %}
		
		<li class="waves-effect"><a href="?page={{page_obj.previous_page_number}}"><i class="fas fa-chevron-circle-left p-1"></i></a></li>
		
		{% endif %}
		<li class="active"><a href="">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</a></li>
		{% if page_obj.has_next %}
		
		<li class="waves-effect"><a href="?page={{page_obj.next_page_number}}"><i class="fas fa-chevron-circle-right p-1"></i></a></li>
		
		{% endif %}
	</ul>
</div>

{% endblock container %}

templates/audit/create_audit.html
{% extends "base.html" %}
{% block title %}
    Create new audit
{% endblock title %}
{% block container %}
	<form action="{% url 'audit:create_audit' %}" method="POST">
		{% csrf_token %}
    	{{form.as_p}}
    	<button class="btn btn-success">Crear!</button>
	</form>
{% endblock container %}

templates/audit/create_numeral.html
{% extends "base.html" %}
{% block title %}
    Crear numeral
{% endblock title %}
{% block container %}
    <div class="container" style="margin-top: 5rem;">
		<div class="jumbotron text-center">
		<h1 class="text-uppercase">Numerales</h1>
		<hr>
		<h5>Crea un nuevo numeral para la norma.</h5>
	</div>
	<!--<div class="pt-5 mt-5"><form action="{% url 'audit:create_numeral' %}" method="POST">
		{% csrf_token %}
    	{{form.as_p}}
    	<button class="btn btn-success">Crear!</button>
	</form>-->
	<div class="container">
        <div class="row justify-content-center">
        <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 border rounded  pt-3 pl-3 pr-3"> 
          {% for error in form.errors %}
            {{error}}
          {% endfor %}
          <form action="{% url 'audit:create_numeral' %}" method="POST">
            {% csrf_token %}
            <div class="form-group font-weight-bold">
              <label for="rule"><i class="fas fa-list-ol pr-1"></i>Norma</label>
             <select class="form-control" id="rule" name="rule">
			      <option selected>-----------</option>
            {% for rule in rules %}
              <option value="{{rule.pk}}">{{rule}}</option>
            {% endfor %}
			    </select>
            </div>
            <div class="form-group font-weight-bold">
              <label for="numeral">#  Numeral</label>
              <input name="numeral" id="numeral" class="form-control"></input>
            </div>
            <div class="form-group font-weight-bold">
              <label for="title"><i class="fas fa-file-signature pr-1"></i>Titulo del Numeral</label>
              <input name="title" id="title" class="form-control"></input>
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-success col"><i class="fas fa-save pr-1"></i>Guardar</button>
            </div>      
            </div>            
          </form>
        </div>
      </div>
      </div>
	</div>
{% endblock container %}	

templates/audit/create_question.html
{% extends "base.html" %}
{% block title %}
Nueva pregunta
{% endblock title %}
{% block container %}
<div class="container" style="margin-top: 5rem;">
  <div class="jumbotron text-center">
    <h1 class="text-uppercase">Preguntas</h1>
    <hr>
    <h5>Crea nuevas preguntas para el numeral deseado.</h5>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 border rounded mb-5 pt-3 pl-3 pr-3"> 
        <form action="{% url 'audit:create_question' %}" method="POST">
          {% csrf_token %}
          <div class="form-group font-weight-bold">
            <label for="numeral">#  Numeral</label>
            <select class="form-control" id="numeral" name="numeral">
              <option selected>---------</option>
              {% for numeral in numerals %}
              <option value="{{numeral.pk}}">{{numeral}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group font-weight-bold">
            <label for="question"><i class="fas fa-question pr-1"></i>Pregunta</label>
            <textarea name="question" id="question" class="form-control"></textarea>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-success col"><i class="fas fa-save pr-1"></i>Guardar</button>
          </div>      
        </form>
      </div>            
    </div>
  </div>
</div>
{% endblock container %}	

templates/audit/create_rule.html
{% extends "base.html" %}
{% block title %}
    Create New Rule
{% endblock title %}
{% block container %}
{% for error in form.errors %}
	{{error}}
{% endfor %}
	<div class="container" style="margin-top: 5rem;">
		<div class="jumbotron text-center">
		<h1 class="text-uppercase">NORMAS</h1>
		<hr>
		<h5>Crea y asigna una nueva norma a un proceso.</h5>
	</div>
	<!--<div class="pt-5 mt-5"><form action="{% url 'audit:create_rule' %}" method="POST">
		{% csrf_token %}
    	{{form.as_p}}
    	<button class="btn btn-success">Crear!</button>
	</form>-->
	<div class="container">
        <div class="row justify-content-center">
        <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 border rounded  pt-3 pl-3 pr-3"> 
          <form action="{% url 'audit:create_rule' %}" method="POST">
            {% csrf_token %}
            <div class="form-group font-weight-bold">
              <label for="process"><i class="fas fa-cog pr-1"></i>Proceso</label>
             <select class="form-control" id="process" name="audit">
              <option selected>--------</option>
              {% for audit in audits %}
                <option value="{{audit.pk}}">{{audit}}</option>
              {% endfor %}
			    </select>
            </div>
            <div class="form-group font-weight-bold">
              <label for=""><i class="fas fa-list-ol pr-1"></i>Norma</label>
              <input name="rule_name" id="" class="form-control"></input>
            </div>
            <div class="form-group font-weight-bold">
              <label for=""><i class="fas fa-file-signature pr-1"></i>Titulo de la Norma</label>
              <input name="rule_title" id="" class="form-control"></input>
            </div>
            <div class="form-group">
              <button class="btn btn-success col"><i class="fas fa-save pr-1"></i>Guardar</button>
            </div>      
            </div>            
          </form>
        </div>
      </div>
      </div>
	</div>
{% endblock container %}

templates/audit/numerals.html
{% extends "base.html" %}
{% block title %}
    {{rule}}
{% endblock title %}
{% block container %}
<div class="container" style="margin-top: 5rem;">
    <div class="jumbotron text-center">
    	<h1 class="text-uppercase">Numerales</h1>
        <hr>
    	<h5>Selecciona el numeral para ver las preguntas.</h5>
    </div>
        <div class="row mt-5 justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-8">
                <div class="table-responsive">
                    <h6 class="text-center">{{rule}}</h6>
                    <table class="table table-striped border text-center">
                        <thead>
                            <tr>
                                <th>Numeral</th>
                                <th>Descripcion</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for numeral in numerals %}
                                <tr>
                                    <th class="align-middle">{{numeral.numeral}}</th>
                                    <td class="align-middle">{{numeral.title}}</td>
                                    <td class="align-middle">
                                        <a href="{% url 'audit:questions' rule.audit.pk rule.pk numeral.pk %}" class="btn btn-info btn-sm "><i class="fas fa-check pr-1"></i>Seleccionar</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <a href="{% url 'audit:create_numeral' %}" class="btn btn-primary btn-sm col mb-5"><i class="fas fa-plus pr-1"></i>AGREGAR MÁS NUMERALES</a>
            </div>
        </div>
</div>
{% endblock container %}

templates/audit/question.html
{% extends "base.html" %}
{% block title %}
    {{question}}
{% endblock title %}
{% block container %}
<div class="container" style="margin-top: 5rem;">
    <div class="jumbotron text-center">
        <h1 class="text-uppercase">Pregunta</h1>
        <hr>
        <h5 class="">{{question}}</h5>
    </div>
    	<div class="row justify-content-center">
    		<div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 border rounded  pt-3 pb-1 mb-5 pl-3 pr-3">	
    			<form action="{% url 'audit:question' question.numeral.rule.audit.pk question.numeral.rule.pk question.numeral.pk question.pk %}" method="POST">
    				{% csrf_token %}
    				<input type="hidden" name="numeral" value="{{question.numeral}}">
    				<input type="hidden" name="question" value="{{question.question}}">
    				<div class="form-group font-weight-bold">
    					<i class="fas fa-file pr-1 ml-2"></i><label for="method">Método</label>
    					<textarea name="method" id="method" class="form-control">{{question.method}}</textarea>
    				</div>
    				{% for error in form.method.errors %}
	    				{{error}}
	    			{% endfor %}
    				<div class="form-group font-weight-bold">
    					<label for="conflict"><i class="fas fa-crosshairs pr-1 ml-1"></i>Conflicto</label>
    						<select name="conflict" id="conflict" class="form-control">
    							{{question.conflict}}
    							{% for option in form.conflict %}
    								{{option}}
    							{% endfor %}
    						</select>
    				</div>
    				{% for error in form.conflict.errors %}
	    				{{error}}
	    			{% endfor %}
    				<div class="form-group font-weight-bold">
    					<label for="conflictDescription"><i class="fas fa-file-signature pr-1 ml-2"></i>Descripción del conflicto encontrado</label>
    					<textarea class="form-control" name="conflict_description" id="conflictDescription"></textarea>
    				</div>
    				{% for error in form.conflict_description.errors %}
	    				{{error}}
	    			{% endfor %}
    				<div class="form-group">
                        <div class="row mt-1">
                            <div class="col-sm-12 col-md-5 col-lg-5">
                                <label class="btn btn-warning text-light col" data-toggle="tooltip" data-placement="bottom" title="Subir foto comprobante.">
                                    <i class="fas fa-camera"></i>
                                    Ingresar evidencia
                                    <input type="file" style="display: none;">
                                </label>
                            </div>
                            <div class="col-sm-12 col-md-7 col-lg-7">
                            {% for error in form.evidence.errors %}
                            {{error}}
                            {% endfor %}
                            <button type="submit" class="btn btn-success col"><i class="fas fa-save pr-1"></i>Guardar</button>
                            </div>
                        </div>			
		 			</div>    				
    			</form>
    		</div>
    	</div>
    </div>
{% endblock container %}

templates/audit/questions.html
{% extends "base.html" %}
{% block title %}
    {{numeral}}
{% endblock title %}
{% block container %}
<div class="container" style="margin-top: 5rem;">
    <div class="jumbotron text-center">
    	<h1 class="text-uppercase">Preguntas</h1>
        <hr>
    	<h5>Selecciona la pregunta para contestarla.</h5>
    </div>
    <div class="container">
    </div>
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-10 col-lg-8 mt-5">
                <div class="table-responsive">
                    <h6 class="text-center">{{numeral}}</h6>
                    <table class="table table-striped border">
                        <thead>
                            <tr>
                                <th class="text-center">Pregunta</th>
                                <th class="text-center">Completed</th>
                                <th class="text-center">Acción</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for question in questions %}
                                <tr>
                                    <td class="align-middle text-justify">{{question.question}}</td>
                                    <td class="text-center align-middle">{% if question.conflict %}<i class="fas fa-check text-success"></i>{% else %}<i class="fas fa-times text-danger"></i>{% endif %}</td>
                                    <td class="text-center align-middle"><a href="{% url 'audit:question' numeral.rule.audit.pk numeral.rule.pk numeral.pk question.pk %}" class="btn btn-info btn-sm">{% if question.conflict %} <i class="fas fa-edit pr-1"></i>Editar</a>{% else %}<i class="far fa-question-circle pr-1"></i>Contestar</a>{% endif %}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <a href="{% url 'audit:create_question' %}" class="btn btn-success btn-sm btn-block text-uppercase mb-4"><i class="fas fa-plus pr-1"></i>Agregar mas preguntas</a>
                {% if last %}                
                <a href="{% url 'audit:questions' numeral.rule.audit.pk numeral.rule.pk last %}" class="btn btn-success">Anterior</a>         
                {% endif %}
                {% if next %}                
                <a href="{% url 'audit:questions' numeral.rule.audit.pk numeral.rule.pk next %}" class="btn btn-success float-right">Siguiente</a>              
                {% endif %}
                
            </div>
        </div>
    </div>
{% endblock container %}

templates/audit/rules.html
{% extends "base.html" %}
{% block title %}
    {{audit}}
{% endblock title %}
{% block container %}
<div class="container" style="margin-top: 5rem;">
	<div class="jumbotron text-center">
		<h1 class="text-uppercase">Normas</h1>
		<hr>
		<h5>Selecciona la norma a auditar.</h5>
	</div>
	<div class="container">
		{% if not audit.rule %}
		    
			<a href="{% url 'audit:create_rule' %}" class="btn btn-success btn-sm btn-block text-uppercase"><i class="fas fa-plus pr-1"></i>Agregar nueva norma</a>
		
		{% endif %}
	</div>
	<div class="row justify-content-center">
		<div class="col-sm-12 col-md-12 col-lg-12 col-xl-7 mt-5 	">
			<div class="table-responsive">
				<h6 class="text-center">{{audit}}</h6>
		    	<table class="table table-striped border text-center">
				    <thead>
				    	<tr>
				      		<th scope="col"># Norma</th>
				      		<th scope="col">Nombre de la Norma</th>
				      		<th scope="col">Acciones</th>
				  		</tr>
				  	</thead>
				  	<tbody>
				    {% for rule in rules %}
					    <tr>
					      	<th scope="row" class="align-middle">{{rule.rule_name}}</th>
					      	<td class="align-middle">{{rule.rule_title}}</td>
					      	<td class="align-middle"><a href="{% url 'audit:numerals' audit.pk rule.pk %}" class="btn btn-info btn-sm"><i class="fas fa-clipboard-check pr-1"></i>Auditar</a>
					      	</td>
					    </tr>
				    {% endfor %}
				  	</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock container %}	